PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE comments (key INTEGER PRIMARY KEY, category_id NUMERIC, comment TEXT);
CREATE TABLE categories (key INTEGER PRIMARY KEY, text TEXT);
INSERT INTO "categories" VALUES(1,'In your opinion, in what ways does the employee excel?');
INSERT INTO "categories" VALUES(2,'In what ways has the employee gone above and beyond their regular call of duty?						');
INSERT INTO "categories" VALUES(3,'Please comment on the employee''s attitude and the overall experience of working with them.');
INSERT INTO "categories" VALUES(4,'How well does the employee execute their job function?');
INSERT INTO "categories" VALUES(5,'Please provide at least one area in which the employee need further improvement.');
INSERT INTO "categories" VALUES(6,'Do you have any other comments or other input not incorporated in the above questions?');
CREATE TABLE feedback (date NUMERIC, key INTEGER PRIMARY KEY, provider_key NUMERIC, target_key NUMERIC, comment_key NUMERIC);
CREATE TABLE employees (supervisor_key NUMERIC, key INTEGER PRIMARY KEY, id TEXT, name TEXT, title TEXT);
COMMIT;
